// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: kad.proto

package kad

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---- Tipi minimi per Store ----
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_kad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_kad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_kad_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Node) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_kad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_kad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_kad_proto_rawDescGZIP(), []int{1}
}

func (x *Key) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type NFTValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         []byte                 `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NFTValue) Reset() {
	*x = NFTValue{}
	mi := &file_kad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NFTValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFTValue) ProtoMessage() {}

func (x *NFTValue) ProtoReflect() protoreflect.Message {
	mi := &file_kad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFTValue.ProtoReflect.Descriptor instead.
func (*NFTValue) Descriptor() ([]byte, []int) {
	return file_kad_proto_rawDescGZIP(), []int{2}
}

func (x *NFTValue) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type StoreReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *Node                  `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Key           *Key                   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         *NFTValue              `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	TtlSecs       int32                  `protobuf:"varint,4,opt,name=ttl_secs,json=ttlSecs,proto3" json:"ttl_secs,omitempty"` // opzionale
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreReq) Reset() {
	*x = StoreReq{}
	mi := &file_kad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReq) ProtoMessage() {}

func (x *StoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_kad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReq.ProtoReflect.Descriptor instead.
func (*StoreReq) Descriptor() ([]byte, []int) {
	return file_kad_proto_rawDescGZIP(), []int{3}
}

func (x *StoreReq) GetFrom() *Node {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *StoreReq) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StoreReq) GetValue() *NFTValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StoreReq) GetTtlSecs() int32 {
	if x != nil {
		return x.TtlSecs
	}
	return 0
}

type StoreRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRes) Reset() {
	*x = StoreRes{}
	mi := &file_kad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRes) ProtoMessage() {}

func (x *StoreRes) ProtoReflect() protoreflect.Message {
	mi := &file_kad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRes.ProtoReflect.Descriptor instead.
func (*StoreRes) Descriptor() ([]byte, []int) {
	return file_kad_proto_rawDescGZIP(), []int{4}
}

func (x *StoreRes) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetNodeListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeListReq) Reset() {
	*x = GetNodeListReq{}
	mi := &file_kad_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeListReq) ProtoMessage() {}

func (x *GetNodeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_kad_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeListReq.ProtoReflect.Descriptor instead.
func (*GetNodeListReq) Descriptor() ([]byte, []int) {
	return file_kad_proto_rawDescGZIP(), []int{5}
}

func (x *GetNodeListReq) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type GetNodeListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"` // qui specifichi che è una lista di Node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeListRes) Reset() {
	*x = GetNodeListRes{}
	mi := &file_kad_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeListRes) ProtoMessage() {}

func (x *GetNodeListRes) ProtoReflect() protoreflect.Message {
	mi := &file_kad_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeListRes.ProtoReflect.Descriptor instead.
func (*GetNodeListRes) Descriptor() ([]byte, []int) {
	return file_kad_proto_rawDescGZIP(), []int{6}
}

func (x *GetNodeListRes) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_kad_proto protoreflect.FileDescriptor

const file_kad_proto_rawDesc = "" +
	"\n" +
	"\tkad.proto\x12\x03kad\">\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"\x17\n" +
	"\x03Key\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\" \n" +
	"\bNFTValue\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\fR\x05bytes\"\x85\x01\n" +
	"\bStoreReq\x12\x1d\n" +
	"\x04from\x18\x01 \x01(\v2\t.kad.NodeR\x04from\x12\x1a\n" +
	"\x03key\x18\x02 \x01(\v2\b.kad.KeyR\x03key\x12#\n" +
	"\x05value\x18\x03 \x01(\v2\r.kad.NFTValueR\x05value\x12\x19\n" +
	"\bttl_secs\x18\x04 \x01(\x05R\attlSecs\"\x1a\n" +
	"\bStoreRes\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"3\n" +
	"\x0eGetNodeListReq\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\"1\n" +
	"\x0eGetNodeListRes\x12\x1f\n" +
	"\x05nodes\x18\x01 \x03(\v2\t.kad.NodeR\x05nodes2j\n" +
	"\bKademlia\x12%\n" +
	"\x05Store\x12\r.kad.StoreReq\x1a\r.kad.StoreRes\x127\n" +
	"\vGetNodeList\x12\x13.kad.GetNodeListReq\x1a\x13.kad.GetNodeListResB\x0fZ\rproto/kad;kadb\x06proto3"

var (
	file_kad_proto_rawDescOnce sync.Once
	file_kad_proto_rawDescData []byte
)

func file_kad_proto_rawDescGZIP() []byte {
	file_kad_proto_rawDescOnce.Do(func() {
		file_kad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kad_proto_rawDesc), len(file_kad_proto_rawDesc)))
	})
	return file_kad_proto_rawDescData
}

var file_kad_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kad_proto_goTypes = []any{
	(*Node)(nil),           // 0: kad.Node
	(*Key)(nil),            // 1: kad.Key
	(*NFTValue)(nil),       // 2: kad.NFTValue
	(*StoreReq)(nil),       // 3: kad.StoreReq
	(*StoreRes)(nil),       // 4: kad.StoreRes
	(*GetNodeListReq)(nil), // 5: kad.GetNodeListReq
	(*GetNodeListRes)(nil), // 6: kad.GetNodeListRes
}
var file_kad_proto_depIdxs = []int32{
	0, // 0: kad.StoreReq.from:type_name -> kad.Node
	1, // 1: kad.StoreReq.key:type_name -> kad.Key
	2, // 2: kad.StoreReq.value:type_name -> kad.NFTValue
	0, // 3: kad.GetNodeListRes.nodes:type_name -> kad.Node
	3, // 4: kad.Kademlia.Store:input_type -> kad.StoreReq
	5, // 5: kad.Kademlia.GetNodeList:input_type -> kad.GetNodeListReq
	4, // 6: kad.Kademlia.Store:output_type -> kad.StoreRes
	6, // 7: kad.Kademlia.GetNodeList:output_type -> kad.GetNodeListRes
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_kad_proto_init() }
func file_kad_proto_init() {
	if File_kad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kad_proto_rawDesc), len(file_kad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kad_proto_goTypes,
		DependencyIndexes: file_kad_proto_depIdxs,
		MessageInfos:      file_kad_proto_msgTypes,
	}.Build()
	File_kad_proto = out.File
	file_kad_proto_goTypes = nil
	file_kad_proto_depIdxs = nil
}
