// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/kad.proto

package kad

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Kademlia_Store_FullMethodName       = "/kad.Kademlia/Store"
	Kademlia_GetNodeList_FullMethodName = "/kad.Kademlia/GetNodeList"
	Kademlia_LookupNFT_FullMethodName   = "/kad.Kademlia/LookupNFT"
)

// KademliaClient is the client API for Kademlia service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---- Servizio ----
type KademliaClient interface {
	Store(ctx context.Context, in *StoreReq, opts ...grpc.CallOption) (*StoreRes, error)
	GetNodeList(ctx context.Context, in *GetNodeListReq, opts ...grpc.CallOption) (*GetNodeListRes, error)
	LookupNFT(ctx context.Context, in *LookupNFTReq, opts ...grpc.CallOption) (*LookupNFTRes, error)
}

type kademliaClient struct {
	cc grpc.ClientConnInterface
}

func NewKademliaClient(cc grpc.ClientConnInterface) KademliaClient {
	return &kademliaClient{cc}
}

func (c *kademliaClient) Store(ctx context.Context, in *StoreReq, opts ...grpc.CallOption) (*StoreRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreRes)
	err := c.cc.Invoke(ctx, Kademlia_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kademliaClient) GetNodeList(ctx context.Context, in *GetNodeListReq, opts ...grpc.CallOption) (*GetNodeListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeListRes)
	err := c.cc.Invoke(ctx, Kademlia_GetNodeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kademliaClient) LookupNFT(ctx context.Context, in *LookupNFTReq, opts ...grpc.CallOption) (*LookupNFTRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupNFTRes)
	err := c.cc.Invoke(ctx, Kademlia_LookupNFT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KademliaServer is the server API for Kademlia service.
// All implementations must embed UnimplementedKademliaServer
// for forward compatibility.
//
// ---- Servizio ----
type KademliaServer interface {
	Store(context.Context, *StoreReq) (*StoreRes, error)
	GetNodeList(context.Context, *GetNodeListReq) (*GetNodeListRes, error)
	LookupNFT(context.Context, *LookupNFTReq) (*LookupNFTRes, error)
	mustEmbedUnimplementedKademliaServer()
}

// UnimplementedKademliaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKademliaServer struct{}

func (UnimplementedKademliaServer) Store(context.Context, *StoreReq) (*StoreRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedKademliaServer) GetNodeList(context.Context, *GetNodeListReq) (*GetNodeListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeList not implemented")
}
func (UnimplementedKademliaServer) LookupNFT(context.Context, *LookupNFTReq) (*LookupNFTRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupNFT not implemented")
}
func (UnimplementedKademliaServer) mustEmbedUnimplementedKademliaServer() {}
func (UnimplementedKademliaServer) testEmbeddedByValue()                  {}

// UnsafeKademliaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KademliaServer will
// result in compilation errors.
type UnsafeKademliaServer interface {
	mustEmbedUnimplementedKademliaServer()
}

func RegisterKademliaServer(s grpc.ServiceRegistrar, srv KademliaServer) {
	// If the following call pancis, it indicates UnimplementedKademliaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Kademlia_ServiceDesc, srv)
}

func _Kademlia_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KademliaServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kademlia_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KademliaServer).Store(ctx, req.(*StoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kademlia_GetNodeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KademliaServer).GetNodeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kademlia_GetNodeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KademliaServer).GetNodeList(ctx, req.(*GetNodeListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kademlia_LookupNFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupNFTReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KademliaServer).LookupNFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kademlia_LookupNFT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KademliaServer).LookupNFT(ctx, req.(*LookupNFTReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Kademlia_ServiceDesc is the grpc.ServiceDesc for Kademlia service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kademlia_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kad.Kademlia",
	HandlerType: (*KademliaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _Kademlia_Store_Handler,
		},
		{
			MethodName: "GetNodeList",
			Handler:    _Kademlia_GetNodeList_Handler,
		},
		{
			MethodName: "LookupNFT",
			Handler:    _Kademlia_LookupNFT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/kad.proto",
}
